export const colors = {
  backgroundPrimary: 'white',
  backgroundSecondary: 'lightblue',
  fontPrimary: '#EEF4ED',
  fontSecondary: '#9EABBB',
  accentGreenDarkest: '#047C5C',
  accentGreenDarker: '#06A77D',
  accentGreen: '#65E4A7',
  accentGreenLighter: '#85FF9E',
  accentGreenLightest: '#D0FFDA',
  accentBlueDarker: '#0B2545',
  accentBlue: '#13315C',
  accentBlueLighter: '#134074',
  accentGrey: '#6E7C8D',
  accentGreyLighter: '#C5CDD6',
  accentDanger: '#FB5959',
  accentDangerLighter: '#FB6E6E',
  accentWarning: '#FFD96B',
  accentInfo: '#71AFF7',
  overlay: 'rgba(0, 0, 0, 0.6)',
}
